{ host, ... }:
let
  vars = import ../../../hosts/${host}/variables.nix;
  inherit (vars)
    barChoice
    browser
    terminal
    ;
  # Noctalia-specific bindings (only included when barChoice == "noctalia")
  noctaliaBind = if barChoice == "noctalia" then [
    "$modifier,D,exec,qs -c noctalia-shell ipc call launcher toggle"
    "$modifier SHIFT,Return,exec,qs -c noctalia-shell ipc call launcher toggle"
    "$modifier,M,exec,qs -c noctalia-shell ipc call notifications toggle"
    "$modifier,V,exec,qs -c noctalia-shell ipc call launcher clipboard"
    "$modifier ALT,P,exec,qs -c noctalia-shell ipc call settings toggle"
    "$modifier SHIFT,comma,exec,qs -c noctalia-shell ipc call settings toggle"
    "$modifier ALT,L,exec,qs -c noctalia-shell ipc call sessionMenu lockAndSuspend"
    "$modifier SHIFT,Y,exec,qs -c noctalia-shell ipc call wallpaper toggle"
    "$modifier,X,exec,dms qs -c noctalia-shell ipc call sessionMenu toggle"
    "$modifier,C,exec,qs -c noctalia-shell ipc call controlCenter toggle"
    "$modifier CTRL,R,exec,qs -c noctalia-shell ipc call screenRecorder toggle"
  ] else [];
in
{
  wayland.windowManager.hyprland.settings = {
    bind = noctaliaBind ++ [
      "$modifier,Return,exec,${terminal}"
      "$modifier,K,exec,list-keybinds"
      "$modifier,D,exec,rofi-launcher"
      "$modifier SHIFT,Return,exec,rofi-launcher"
      "$modifier SHIFT,D,exec,discord"
      "$modifier SHIFT,W,exec,web-search"
      "$modifier ALT,W,exec,wallsetter"
      "$modifier SHIFT,N,exec,swaync-client -rs"
      "$modifier,W,exec,${browser}"
      "$modifier,Y,exec,kitty -e yazi"
      "$modifier,E,exec,emopicker9000"
      "$modifier,S,exec,screenshootin"
      "$modifier CTRL,S,exec,hyprshot -m output -o $HOME/Pictures/ScreenShots"
      "$modifier SHIFT,S,exec,hyprshot -m window -o $HOME/Pictures/ScreenShots"
      "$modifier ALT,S,exec,hyprshot -m region -o $HOME/Pictures/ScreenShots"
      "$modifier,O,exec,obs"
      "$modifier ALT,C,exec,hyprpicker -a"
      "$modifier,G,exec,gimp"
      "$modifier shift,T,exec,pypr toggle term"
      "$modifier,T,exec, thunar"
      "$modifier ALT,M,exec,pavucontrol"
      "$modifier,Q,killactive,"
      "$modifier,P,pseudo,"
      "$modifier,V,exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy"
      "$modifier SHIFT,I,togglesplit,"
      "$modifier,F,fullscreen,"
      "$modifier SHIFT,F,togglefloating,"
      "$modifier ALT,F,workspaceopt, allfloat"
      "$modifier SHIFT,C,exit,"
      "$modifier SHIFT,left,movewindow,l"
      "$modifier SHIFT,right,movewindow,r"
      "$modifier SHIFT,up,movewindow,u"
      "$modifier SHIFT,down,movewindow,d"
      "$modifier SHIFT,h,movewindow,l"
      "$modifier SHIFT,l,movewindow,r"
      "$modifier SHIFT,k,movewindow,u"
      "$modifier SHIFT,j,movewindow,d"
      "$modifier ALT, left, swapwindow,l"
      "$modifier ALT, right, swapwindow,r"
      "$modifier ALT, up, swapwindow,u"
      "$modifier ALT, down, swapwindow,d"
      "$modifier ALT, 43, swapwindow,l"
      "$modifier ALT, 46, swapwindow,r"
      "$modifier ALT, 45, swapwindow,u"
      "$modifier ALT, 44, swapwindow,d"
      "$modifier,left,movefocus,l"
      "$modifier,right,movefocus,r"
      "$modifier,up,movefocus,u"
      "$modifier,down,movefocus,d"
      "$modifier,h,movefocus,l"
      "$modifier,l,movefocus,r"
      "$modifier,k,movefocus,u"
      "$modifier,j,movefocus,d"
      "$modifier,1,workspace,1"
      "$modifier,2,workspace,2"
      "$modifier,3,workspace,3"
      "$modifier,4,workspace,4"
      "$modifier,5,workspace,5"
      "$modifier,6,workspace,6"
      "$modifier,7,workspace,7"
      "$modifier,8,workspace,8"
      "$modifier,9,workspace,9"
      "$modifier,0,workspace,10"
      "$modifier SHIFT,SPACE,movetoworkspace,special"
      "$modifier,SPACE,togglespecialworkspace"
      "$modifier SHIFT,1,movetoworkspace,1"
      "$modifier SHIFT,2,movetoworkspace,2"
      "$modifier SHIFT,3,movetoworkspace,3"
      "$modifier SHIFT,4,movetoworkspace,4"
      "$modifier SHIFT,5,movetoworkspace,5"
      "$modifier SHIFT,6,movetoworkspace,6"
      "$modifier SHIFT,7,movetoworkspace,7"
      "$modifier SHIFT,8,movetoworkspace,8"
      "$modifier SHIFT,9,movetoworkspace,9"
      "$modifier SHIFT,0,movetoworkspace,10"
      "$modifier CONTROL,right,workspace,e+1"
      "$modifier CONTROL,left,workspace,e-1"
      "$modifier,mouse_down,workspace, e+1"
      "$modifier,mouse_up,workspace, e-1"
      "ALT,Tab,cyclenext"
      "ALT,Tab,bringactivetotop"
      ",XF86AudioRaiseVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
      ",XF86AudioLowerVolume,exec,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
      " ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
      ",XF86AudioPlay, exec, playerctl play-pause"
      ",XF86AudioPause, exec, playerctl play-pause"
      ",XF86AudioNext, exec, playerctl next"
      ",XF86AudioPrev, exec, playerctl previous"
      ",XF86MonBrightnessDown,exec,brightnessctl set 5%-"
      ",XF86MonBrightnessUp,exec,brightnessctl set +5%"
    ];

    bindm = [
      "$modifier, mouse:272, movewindow"
      "$modifier, mouse:273, resizewindow"
    ];
  };
}
