# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  host,
  inputs,
  lib,
  pkgs,
  modulesPath,
  username,
  ...
}: {
  imports = [
    inputs.nixos-wsl.nixosModules.default
  ];

  wsl = {
    enable = true;
    useWindowsDriver = true;
    defaultUser = username;
    interop.register = true;
  };

  environment.systemPackages = with pkgs; [
    wl-clipboard
    wsl-open
    xdg-utils
  ];

  nixpkgs.overlays = [
    (_final: prev: {
      xdg-utils = prev.symlinkJoin {
        name = "xdg-utils-wsl";
        paths = [prev.xdg-utils];
        postBuild = ''
          ln -sf ${prev.wsl-open}/bin/wsl-open $out/bin/xdg-open
        '';
      };
    })
  ];

  nixpkgs.hostPlatform = "aarch64-linux";
}
